// mutation 常量
export const UPDATE_USERINFO = 'UPDATE_USERINFO'
export const UPDATE_USERINFO_LOGO = 'UPDATE_USERINFO_LOGO'
export const UPDATE_USERINFO_SEX = 'UPDATE_USERINFO_SEX'
export const UPDATE_USERINFO_BIRTH = 'UPDATE_USERINFO_BIRTH'
export const UPDATE_USERINFO_CITY = 'UPDATE_USERINFO_CITY'
export const UPDATE_USERINFO_NICKNAME = 'UPDATE_USERINFO_NICKNAME'
export const UPDATE_USERINFO_LASTPHONE = 'UPDATE_USERINFO_LASTPHONE'
export const UPDATE_USERINFO_PHONE = 'UPDATE_USERINFO_PHONE'
